/**
 * Service: Custom Software & App Development (monthly subscription)
 *
 * Content for the /[lang]/software-a-la-medida landing page
 */

import type { CustomSoftwareContent } from '../es/custom-software';

export const customSoftwareEn: CustomSoftwareContent = {
  seo: {
    title: 'Custom Software Development in Guatemala from Q2,500/month | GDS',
    description:
      'Custom software and app development in Guatemala as a subscription from Q2,500 per month: web systems, mobile apps, FEL e-invoicing, payments and WhatsApp integrations. Hosting, support and monthly improvements included. Free assessment.',
    keywords: [
      'custom software development Guatemala',
      'software development company Guatemala',
      'app development Guatemala',
      'custom web application development',
      'mobile app development Central America',
      'software development subscription',
      'nearshore software development Guatemala',
      'FEL SAT integration',
    ],
  },
  breadcrumb: { home: 'Home', current: 'Custom software' },
  hero: {
    badge: 'New · From Q2,500 per month',
    title: 'Custom software and apps for your business, for a fixed monthly fee',
    description:
      'We design, build, host and improve your web system or mobile app every month. No large upfront payment and no need to hire a team of developers. You bring the idea; we turn it into software that works.',
    primaryCta: 'Book a free assessment',
    secondaryCta: 'Get a quote on WhatsApp',
    trust: [
      'Team based in Guatemala',
      'First version in weeks, not months',
      'Hosting, support and improvements included',
      'Your data is always yours',
    ],
  },
  problem: {
    title: 'Sound familiar?',
    items: [
      { title: 'Your operation runs on Excel and WhatsApp', description: 'Orders, quotes, inventory and collections scattered across spreadsheets and chats. Information gets lost and nobody has the right numbers.' },
      { title: 'Off-the-shelf software does not fit', description: 'You pay for features you do not use and still miss what your process really needs.' },
      { title: 'Custom projects seem out of reach', description: 'Traditional quotes require a large upfront payment, take months and then charge extra for every change and for maintenance.' },
      { title: 'The freelancer disappeared', description: 'Systems without documentation, without backups and without anyone to call when something breaks.' },
    ],
  },
  whatWeBuild: {
    title: 'What we build',
    description: 'Real solutions for real processes. If your company does it, we can digitize it.',
    items: [
      { icon: '🖥️', title: 'Custom web systems', description: 'Inventory, quotes, work orders, collections, payroll, project control and intranets.' },
      { icon: '📱', title: 'Android and iOS apps', description: 'Apps for sales reps, field technicians, drivers and customers, with offline support.' },
      { icon: '🛒', title: 'Portals and online stores', description: 'Customer and supplier portals, catalogs, B2B ordering and e-commerce with online payments.' },
      { icon: '🔗', title: 'Integrations and automation', description: 'FEL e-invoicing, banks, payment gateways, WhatsApp, ERP, email and third-party APIs.' },
      { icon: '📊', title: 'Dashboards and reports', description: 'Real-time KPIs, automated reports and Business Intelligence dashboards.' },
      { icon: '🤖', title: 'Applied AI', description: 'Chatbots, customer service assistants, document reading and AI-powered automation.' },
    ],
  },
  plans: {
    title: 'Custom development plans',
    description: 'One fixed monthly fee that covers development, infrastructure, support and the continuous evolution of your software.',
    items: [
      {
        id: 'esencial',
        name: 'Essential',
        price: 'Q2,500',
        priceNote: '/month',
        priceValue: 2500,
        tagline: 'Digitize one key process of your business',
        features: [
          '1 custom web system or web app (PWA)',
          'Initial development included per the assessment scope',
          'Up to 10 hours per month of improvements and new features',
          'Up to 10 users',
          'Cloud hosting, domain with SSL and daily backups',
          'WhatsApp and email support during business hours',
          'Training for your team',
        ],
        cta: 'Start with Essential',
        whatsappMessage: 'Hi GDS, I am interested in the Essential custom software plan (Q2,500/month). I would like to book an assessment.',
      },
      {
        id: 'profesional',
        name: 'Professional',
        price: 'Q5,900',
        priceNote: '/month',
        priceValue: 5900,
        tagline: 'For companies that need web + app and integrations',
        features: [
          'Web system + Android/iOS app (or 2 web systems)',
          'Up to 25 hours per month of improvements and new features',
          'Up to 50 users',
          'Integrations: FEL, payment gateway, WhatsApp or your ERP',
          'KPI dashboard',
          'Priority support and monitoring',
          'Monthly follow-up and roadmap meeting',
        ],
        cta: 'Start with Professional',
        whatsappMessage: 'Hi GDS, I am interested in the Professional custom software plan (Q5,900/month). I would like to book an assessment.',
        highlighted: true,
      },
      {
        id: 'empresarial',
        name: 'Enterprise',
        price: 'Custom',
        priceNote: '',
        tagline: 'Dedicated team for large or critical projects',
        features: [
          'Dedicated developer or squad',
          'Architecture, QA and DevOps included',
          'Unlimited users and staging environments',
          'Complex integrations and high availability',
          'Service level agreement (SLA)',
          'Assigned project manager',
        ],
        cta: 'Request a proposal',
        whatsappMessage: 'Hi GDS, I need a proposal for custom development with a dedicated team.',
      },
    ],
    footnote:
      'Prices in Guatemalan quetzales (GTQ), VAT not included. 12-month minimum term. The initial development scope is defined in writing during the free assessment. One-time project pricing is also available.',
  },
  included: {
    title: 'Everything included in your monthly fee',
    items: [
      'Solution analysis and design (UX/UI)',
      'Development, testing and deployment',
      'Cloud servers, domain and SSL certificate',
      'Automatic daily backups',
      'Security updates',
      'Technical support in Spanish and English',
      'Improvements and new features every month',
      'Documentation and training',
    ],
  },
  process: {
    title: 'How we work',
    description: 'A clear process so you know what you get, when and how much it costs.',
    steps: [
      { title: '1. Free assessment', description: 'A 30 to 45 minute call to understand your process, your users and your goals.' },
      { title: '2. Proposal and prototype', description: 'We present the scope, the recommended plan and a clickable prototype before you sign.' },
      { title: '3. Development in sprints', description: 'Deliveries every two weeks with a demo, so you see progress and adjust in time.' },
      { title: '4. Launch', description: 'We publish your system, migrate your data and train your team.' },
      { title: '5. Continuous improvement', description: 'Every month we use your improvement hours to add features based on your business priorities.' },
    ],
  },
  comparison: {
    title: 'Why a subscription instead of a traditional project?',
    description: 'Compare the most common ways to get your own software.',
    columns: ['GDS subscription', 'In-house developer', 'Freelancer', 'Traditional agency'],
    rows: [
      { label: 'Upfront investment', values: ['Low', 'Hiring and equipment', 'Medium', 'High'] },
      { label: 'Predictable monthly cost', values: ['✅ Fixed', '⚠️ Salary + benefits', '❌ Variable', '❌ Changes cost extra'] },
      { label: 'Hosting, backups and security', values: ['✅ Included', '❌ Separate', '❌ Separate', '⚠️ Separate'] },
      { label: 'Continuous improvements', values: ['✅ Every month', '✅', '⚠️ When available', '❌ New quote'] },
      { label: 'Continuity if someone leaves', values: ['✅ Team and documentation', '❌ High risk', '❌ High risk', '⚠️'] },
      { label: 'Design, QA and DevOps', values: ['✅ Included', '❌', '❌', '✅'] },
    ],
  },
  useCases: {
    title: 'Examples by industry',
    items: [
      { industry: 'Distribution and retail', examples: 'Route order taking, inventory control, collections and sales commissions.' },
      { industry: 'Clinics and healthcare', examples: 'Appointment scheduling, medical records, WhatsApp reminders and billing.' },
      { industry: 'Restaurants', examples: 'Online ordering, ingredient control, recipes and cash closings by branch.' },
      { industry: 'Construction', examples: 'Site progress, warehouses, requisitions, payroll and photo logs.' },
      { industry: 'Field services', examples: 'Work orders, field technicians with an app, digital signatures and customer reports.' },
      { industry: 'Education', examples: 'Enrollment, tuition payments, grades and parent communication.' },
      { industry: 'Logistics', examples: 'Shipment tracking, proof of delivery, routes and customer portal.' },
      { industry: 'Manufacturing', examples: 'Production orders, quality control, lot traceability and maintenance.' },
    ],
  },
  integrations: {
    title: 'Integrated with the tools you already use',
    description: 'We connect your software with the services your operation needs in Guatemala and the region.',
    items: [
      'FEL e-invoicing (SAT Guatemala)',
      'Payment gateways and banks',
      'WhatsApp Business API',
      'GDS ONE ERP',
      'Google Workspace and Microsoft 365',
      'Power BI and Looker Studio',
      'Email and SMS',
      'Third-party REST APIs',
    ],
  },
  whyGds: {
    title: 'Why GDS',
    items: [
      { title: 'Business expertise', description: 'We are the team behind GDS ONE ERP. We understand accounting, inventory, sales and operations, not just code.' },
      { title: 'Local team', description: 'Service in Spanish and English, in your time zone, with in-person meetings in Guatemala when needed.' },
      { title: 'Modern technology', description: 'Web and mobile applications built with current technologies, in the cloud, secure and ready to scale.' },
      { title: 'No surprises', description: 'Fixed monthly fee, written scope and deliveries every two weeks that you can test.' },
    ],
  },
  faq: {
    title: 'Frequently asked questions',
    items: [
      { question: 'How much does custom software development cost in Guatemala?', answer: 'With GDS you can start from Q2,500 per month (Essential plan) with development, hosting, support and improvements included. A traditional one-time project usually requires a large upfront investment plus separate hosting and maintenance costs. We give you an exact quote during the free assessment.' },
      { question: 'What does the monthly fee include?', answer: 'Analysis, design, development and testing; cloud servers, domain and SSL; daily backups; security updates; technical support and a monthly bank of hours for improvements and new features.' },
      { question: 'How long until my system is ready?', answer: 'It depends on the scope. We work in two-week sprints and aim to deliver a first working version within a few weeks, then keep adding features every month.' },
      { question: 'Is there a minimum contract term?', answer: 'Yes, monthly plans have a 12-month minimum term because the initial development is included in the monthly fee. After that you can continue month to month.' },
      { question: 'Who owns the software and the data?', answer: 'Your data is always yours and you can export it at any time. The conditions for transferring the source code are clearly defined in the contract before we start.' },
      { question: 'Can you build an app for Android and iPhone?', answer: 'Yes. We build mobile apps for Android and iOS, as well as progressive web apps (PWA) that install from the browser without going through the app stores.' },
      { question: 'Can it integrate with SAT FEL e-invoicing?', answer: 'Yes. We integrate your system with FEL certifiers, payment gateways, banks, WhatsApp Business and other systems through APIs.' },
      { question: 'What if I need more hours or features?', answer: 'You can upgrade your plan at any time or buy additional hours. Unused hours do not roll over to the next month.' },
      { question: 'Do you work with companies outside Guatemala?', answer: 'Yes. We serve companies across Central and Latin America remotely, and we can invoice in US dollars for clients outside Guatemala.' },
      { question: 'How is this different from GDS ONE ERP?', answer: 'GDS ONE is our ready-to-use ERP. Custom development is for processes unique to your company; we can also build modules or apps that integrate with GDS ONE or any other ERP.' },
    ],
  },
  form: {
    title: 'Tell us about your project',
    description: 'We reply on WhatsApp during business hours to schedule your free assessment.',
    name: 'Name',
    company: 'Company',
    phone: 'Phone / WhatsApp',
    projectType: 'Project type',
    projectTypes: ['Web system', 'Mobile app', 'Web + App', 'Integration / automation', 'Online store or portal', 'Not sure yet'],
    plan: 'Plan of interest',
    planOptions: ['Essential (Q2,500/month)', 'Professional (Q5,900/month)', 'Enterprise', 'I need advice'],
    details: 'Which process do you want to digitize?',
    detailsPlaceholder: 'E.g.: we need an app for sales reps to take orders on the road and update inventory.',
    submit: 'Send via WhatsApp',
    privacy: 'By submitting you accept our privacy policy. We do not share your data.',
    whatsappIntro: 'Hi GDS, I would like a quote for custom software development.',
  },
  finalCta: {
    title: 'Turn your process into software this season',
    description: 'Book a free 30-minute assessment. No commitment.',
    button: 'Talk to a consultant',
  },
};
